[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[context.production]
  SECRETS_SCAN_OMIT_KEYS = "GOOGLE_API_KEY"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
